"""update enum

Revision ID: 2738cdb78bd2
Revises: d5a9d2d4bae1
Create Date: 2025-01-12 20:02:31.439889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2738cdb78bd2'
down_revision: Union[str, None] = 'd5a9d2d4bae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
